In [2]:
import pandas as pd
import numpy as np

#Donnees indices

In [3]:
xls = pd.ExcelFile('Compo_All_Indices_20260731_copy.xlsx')
sheet_names = xls.sheet_names
print(f"Sheets in the Excel file: {sheet_names}")

Sheets in the Excel file: ['MASI', 'Sector Indices', 'MASI 20', 'MASI ESG', 'MASI Mid and Small Cap']

Now, you can read all sheets into a dictionary where each key is the sheet name and each value is a pandas DataFrame.

In [4]:
all_sheets_df = pd.read_excel('Compo_All_Indices_20260731_copy.xlsx', sheet_name=None)

# To see the data for a specific sheet, you can access it like this:
# For example, to see the head of the first sheet:
for num, sheet_name in enumerate(sheet_names, 1):
    print(f"\nDisplaying the head of the {num} sheet ('{sheet_name}'):")
    display(all_sheets_df[sheet_name].head())

Displaying the head of the 1 sheet ('MASI'):

,Séance,Indice,Code ISIN,Instrument,Cours,Nombre de titres,Facteur flottant,Facteur de plafonnement,Capitalisation flottante,Poids
0,2026-07-31,MASI,MA0000012445,ATTIJARIWAFA BANK,685.0,215140839,0.30,1,4.421144e+10,0.165426
1,2026-07-31,MASI,MA0000012866,MANAGEM,1319.0,118646760,0.15,1,2.347426e+10,0.087833
2,2026-07-31,MASI,MA0000012312,SODEP-Marsa Maroc,860.0,73395600,0.35,1,2.209208e+10,0.082662
3,2026-07-31,MASI,MA0000011488,ITISSALAT AL-MAGHRIB,92.5,879095340,0.20,1,1.626326e+10,0.060852
4,2026-07-31,MASI,MA0000012320,Holcim Maroc S.A,1769.0,23431240,0.35,1,1.450745e+10,0.054282

Displaying the head of the 2 sheet ('Sector Indices'):

,Séance,Code Indice,Indice,Code ISIN,Instrument,Cours,Nombre de titres,Facteur flottant,Facteur de plafonnement,Capitalisation flottante,Poids
0,2026-07-31,AGRO,MASI AGROALIMENTAIRE / PRODUCTION,MA0000012247,COSUMAR,186.0,94487143,0.30,1,5.272383e+09,0.534586
1,2026-07-31,AGRO,MASI AGROALIMENTAIRE / PRODUCTION,MA0000012031,LESIEUR CRISTAL,306.9,27631510,0.25,1,2.120028e+09,0.214957
2,2026-07-31,AGRO,MASI AGROALIMENTAIRE / PRODUCTION,MA0000012395,MUTANDIS SCA,226.1,9246737,0.80,1,1.672550e+09,0.169586
3,2026-07-31,AGRO,MASI AGROALIMENTAIRE / PRODUCTION,MA0000012023,UNIMER,177.0,11413880,0.20,1,4.040514e+08,0.040968
4,2026-07-31,AGRO,MASI AGROALIMENTAIRE / PRODUCTION,MA0000011421,DARI COUSPATE,4060.0,298375,0.30,1,3.634208e+08,0.036849

Displaying the head of the 3 sheet ('MASI 20'):

,Séance,Indice,Code ISIN,Instrument,Cours,Nombre de titres,Facteur Flottant,Facteur de plafonnement,Capitalisation flottante,Poids
0,2026-07-31,MASI 20,MA0000012445,ATTIJARIWAFA BANK,685.0,215140839,0.30,0.8568,3.788036e+10,0.212354
1,2026-07-31,MASI 20,MA0000012312,SODEP-Marsa Maroc,860.0,73395600,0.35,1.0000,2.209208e+10,0.123846
2,2026-07-31,MASI 20,MA0000011488,ITISSALAT AL-MAGHRIB,92.5,879095340,0.20,1.0000,1.626326e+10,0.091170
3,2026-07-31,MASI 20,MA0000012320,Holcim Maroc S.A,1769.0,23431240,0.35,1.0000,1.450745e+10,0.081327
4,2026-07-31,MASI 20,MA0000012437,BANK OF AFRICA,188.0,220281881,0.25,1.0000,1.035325e+10,0.058039

Displaying the head of the 4 sheet ('MASI ESG'):

,Séance,Indice,Code ISIN,Instrument,Cours,Nombre de titres,Facteur 1,Facteur de plafonnement,Capitalisation flottante,Poids
0,2026-07-31,MASI ESG,MA0000012866,MANAGEM,1319.0,118646760,0.0452,1.0000,7.073577e+09,0.218939
1,2026-07-31,MASI ESG,MA0000012445,ATTIJARIWAFA BANK,685.0,215140839,0.0567,0.7151,5.975349e+09,0.184947
2,2026-07-31,MASI ESG,MA0000011488,ITISSALAT AL-MAGHRIB,92.5,879095340,0.0467,1.0000,3.797472e+09,0.117538
3,2026-07-31,MASI ESG,MA0000012312,SODEP-Marsa Maroc,860.0,73395600,0.0441,1.0000,2.783602e+09,0.086157
4,2026-07-31,MASI ESG,MA0000012437,BANK OF AFRICA,188.0,220281881,0.0571,1.0000,2.364682e+09,0.073191

Displaying the head of the 5 sheet ('MASI Mid and Small Cap'):

,Séance,Indice,Code ISIN,Instrument,Cours,Nombre de titres,Facteur Flottant,Facteur de plafonnement,Capitalisation flottante,Poids
0,2026-07-31,MASI Mid and Small Cap,MA0000011793,MINIERE TOUISSIT,4350.0,1681233,0.50,1.0000,3.656682e+09,0.086574
1,2026-07-31,MASI Mid and Small Cap,MA0000012627,CFG BANK,195.0,35007960,0.85,0.6011,3.487924e+09,0.082578
2,2026-07-31,MASI Mid and Small Cap,MA0000012460,ARADEI CAPITAL,428.0,12568130,0.60,1.0000,3.227496e+09,0.076412
3,2026-07-31,MASI Mid and Small Cap,MA0000012619,HPS,594.0,7406190,0.65,1.0000,2.859530e+09,0.067701
4,2026-07-31,MASI Mid and Small Cap,MA0000012718,CMGP GROUP,324.0,17000900,0.50,1.0000,2.754146e+09,0.065206

# Donnees marche

In [5]:
xls_ = pd.ExcelFile('Données Marché Boursier_Projet_IA_copy.xlsx')
sheet_names_ = xls_.sheet_names
print(f"Sheets in the Excel file: {sheet_names_}")

Sheets in the Excel file: ['Data', 'Cours', 'Bid', 'Ask', 'Quantité MC', 'Volume MC', 'Indicateurs']

In [6]:
all_sheets_df_ = pd.read_excel('Données Marché Boursier_Projet_IA_copy.xlsx', sheet_name=None)

# To see the data for a specific sheet, you can access it like this:
# For example, to see the head of the first sheet:
for num, sheet_name in enumerate(sheet_names_, 1):
    print(f"\nDisplaying the head of the {num} sheet ('{sheet_name}'):")
    display(all_sheets_df_[sheet_name].head())

Displaying the head of the 1 sheet ('Data'):

,Code AMC,1229,1211,1095,1094,1258,1181,1093,1246,1171,...,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94
0,CODE ISIN,MA0000012296,MA0000012114,MA0000010951,MA0000010944,MA0000012585,MA0000011819,MA0000010936,MA0000012460,MA0000011710,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,LIBELLE,AFMA,AFRIC INDUSTRIES SA,AFRIQUIA GAZ,AGMA,AKDITAL,ALLIANCES,ALUMINIUM DU MAROC,ARADEI CAPITAL,ATLANTASANAD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,"MA0000012296,XX,CAS","MA0000012114,XX,CAS","MA0000010951,XX,CAS","MA0000010944,XX,CAS","MA0000012585,XX,CAS","MA0000011819,XX,CAS","MA0000010936,XX,CAS","MA0000012460,XX,CAS","MA0000011710,XX,CAS",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,AFMA P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,ALTHIGHMID,ALTLOWMID,BASK,BBID,PERF-1YR,PERF-5YRSANN,52W-LOW,YLO,LOWOFF,...,YLO,LOWOFF,YRLOW,HIGHPRICE,52W-HIGH,HVOLA180,HVOLA250,HVOLA30,HVOLA90,VWAP

Displaying the head of the 2 sheet ('Cours'):

,Code AMC,1229,1211,1095,1094,1258,1181,1093
0,CODE ISIN,MA0000012296,MA0000012114,MA0000010951,MA0000010944,MA0000012585,MA0000011819,MA0000010936
1,LIBELLE,AFMA,AFRIC INDUSTRIES SA,AFRIQUIA GAZ,AGMA,AKDITAL,ALLIANCES,ALUMINIUM DU MAROC
2,NaN,"MA0000012296,XX,CAS","MA0000012114,XX,CAS","MA0000010951,XX,CAS","MA0000010944,XX,CAS","MA0000012585,XX,CAS","MA0000011819,XX,CAS","MA0000010936,XX,CAS"
3,NaN,AFMA P,Afric Indus.,Afriquia Gaz P,Agma P,Akdital Br,Alliances P,Aluminium Maroc P
4,NaN,VAL,VAL,VAL,VAL,VAL,VAL,VAL

Displaying the head of the 3 sheet ('Bid'):

,Code AMC,1229,1211,1095,1094,1258,1181,1093
0,CODE ISIN,MA0000012296,MA0000012114,MA0000010951,MA0000010944,MA0000012585,MA0000011819,MA0000010936
1,LIBELLE,AFMA,AFRIC INDUSTRIES,AFRIQUIA GAZ,AGMA,AKDITAL,ALLIANCES,ALUMINIUM DU MAROC
2,NaN,"MA0000012296,XX,CAS","MA0000012114,XX,CAS","MA0000010951,XX,CAS","MA0000010944,XX,CAS","MA0000012585,XX,CAS","MA0000011819,XX,CAS","MA0000010936,XX,CAS"
3,NaN,AFMA P,Afric Indus.,Afriquia Gaz P,Agma P,Akdital Br,Alliances P,Aluminium Maroc P
4,NaN,BBID,BBID,BBID,BBID,BBID,BBID,BBID

Displaying the head of the 4 sheet ('Ask'):

,Code AMC,1229,1211,1095,1094,1258,1181,1093
0,CODE ISIN,MA0000012296,MA0000012114,MA0000010951,MA0000010944,MA0000012585,MA0000011819,MA0000010936
1,LIBELLE,AFMA,AFRIC INDUSTRIES,AFRIQUIA GAZ,AGMA,AKDITAL,ALLIANCES,ALUMINIUM DU MAROC
2,NaN,"MA0000012296,XX,CAS","MA0000012114,XX,CAS","MA0000010951,XX,CAS","MA0000010944,XX,CAS","MA0000012585,XX,CAS","MA0000011819,XX,CAS","MA0000010936,XX,CAS"
3,NaN,AFMA P,Afric Indus.,Afriquia Gaz P,Agma P,Akdital Br,Alliances P,Aluminium Maroc P
4,NaN,BASK,BASK,BASK,BASK,BASK,BASK,BASK

Displaying the head of the 5 sheet ('Quantité MC'):

,CODE ISIN,MA0000012296,MA0000012114,MA0000010951,MA0000010944,MA0000012585,MA0000011819,MA0000010936
0,LIBELLE,AFMA,AFRIC INDUSTRIES SA,AFRIQUIA GAZ,AGMA,AKDITAL,ALLIANCES,ALUMINIUM DU MAROC
1,NaN,"MA0000012296,XX,CAS","MA0000012114,XX,CAS","MA0000010951,XX,CAS","MA0000010944,XX,CAS","MA0000012585,XX,CAS","MA0000011819,XX,CAS","MA0000010936,XX,CAS"
2,NaN,AFMA P,Afric Indus.,Afriquia Gaz P,Agma P,Akdital Br,Alliances P,Aluminium Maroc P
3,NaN,CUMVOL,CUMVOL,CUMVOL,CUMVOL,CUMVOL,CUMVOL,CUMVOL
4,2018-12-31 00:00:00,1,NaN,NaN,NaN,NaN,23948,NaN

Displaying the head of the 6 sheet ('Volume MC'):

,Code AMC,1229,1211,1095,1094,1258,1181,1093
0,CODE ISIN,MA0000012296,MA0000012114,MA0000010951,MA0000010944,MA0000012585,MA0000011819,MA0000010936
1,LIBELLE,AFMA,AFRIC INDUSTRIES SA,AFRIQUIA GAZ,AGMA,AKDITAL,ALLIANCES,ALUMINIUM DU MAROC
2,NaN,"MA0000012296,XX,CAS","MA0000012114,XX,CAS","MA0000010951,XX,CAS","MA0000010944,XX,CAS","MA0000012585,XX,CAS","MA0000011819,XX,CAS","MA0000010936,XX,CAS"
3,NaN,AFMA P,Afric Indus.,Afriquia Gaz P,Agma P,Akdital Br,Alliances P,Aluminium Maroc P
4,NaN,CUMTUR,CUMTUR,CUMTUR,CUMTUR,CUMTUR,CUMTUR,CUMTUR

Displaying the head of the 7 sheet ('Indicateurs'):

,Valuation price,Unnamed: 1,Previous Valuation Price,Unnamed: 3,Change on 1 week,Unnamed: 5,Change on 4 weeks,Unnamed: 7,Change on 12 weeks,Unnamed: 9,...,Av. Volume over 52 weeks,Unnamed: 35,Year High,Unnamed: 37,Previous Year High,Unnamed: 39,Actual Year Low,Unnamed: 41,Previous Year Low,Unnamed: 43
0,Valeur,Date,Valeur,Date,Valeur,Date,Valeur,Date,Valeur,Date,...,Valeur,Date,Valeur,Date,Valeur,Date,Valeur,Date,Valeur,Date
1,Val,h Val,P-Val,d P-Val,Bar Net 1W%,d Bar Net 1W%,4W % Val Bar,d 4W % Val Bar,12W % Val Bar,d 12W % Val Bar,...,52W-AvVol,d 52W-AvVol,Y-Hi,d Y-Hi,PY-Hi,d PY-Hi,Y-Lo,d Y-Lo,PY-Lo,d PY-Lo

In [7]:
df = pd.read_excel('Data_sheet_without_legend.xlsx')
df.head()

,Unnamed: 0,AFMA P,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 85,Unnamed: 86,Unnamed: 87,Unnamed: 88,Unnamed: 89,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94
0,NaT,ALTHIGHMID,ALTLOWMID,BASK,BBID,PERF-1YR,PERF-5YRSANN,52W-LOW,YLO,LOWOFF,...,YLO,LOWOFF,YRLOW,HIGHPRICE,52W-HIGH,HVOLA180,HVOLA250,HVOLA30,HVOLA90,VWAP
1,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-07-21,NaN,NaN,1279,1231,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,193.7,NaN,NaN,NaN,NaN,NaN,187.838554
3,2026-07-20,NaN,NaN,1279,1230,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,189.95,NaN,33.91,32.91,12.67,25.58,185.274305
4,2026-07-17,NaN,NaN,1279,1200,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,192.8,NaN,34.47,32.92,15.73,25.67,188.531934

In [9]:
import sys, os
from pathlib import Path
sys.path.insert(0, os.path.abspath('..'))
from src.ingestion import ingest_workbook

files = [
    'Compo_All_Indices_20260731_copy.xlsx',
    'Données Marché Boursier_Projet_IA_copy.xlsx',
    'Data_sheet_without_legend.xlsx'
]

for f in files:
    p = Path(f)
    print('Processing', p.name)
    df = ingest_workbook(str(p))
    print('Unified shape for', p.name, ':', df.shape)
    display(df.head())

Processing Compo_All_Indices_20260731_copy.xlsx
Parsed sheet MASI -> 171 rows
Parsed sheet Sector Indices -> 190 rows
Parsed sheet MASI 20 -> 171 rows
Parsed sheet MASI ESG -> 171 rows
Parsed sheet MASI Mid and Small Cap -> 171 rows
Unified shape for Compo_All_Indices_20260731_copy.xlsx : (38, 8)

,Date,CODE_ISIN,Company,MASI,MASI 20,MASI ESG,MASI Mid and Small Cap,Sector Indices
0,2026-07-31,Capitalisation flottante,3656681775,NaN,NaN,NaN,3656681775,NaN
1,2026-07-31,Capitalisation flottante,37880363860.7436,NaN,37880363860.743599,NaN,NaN,NaN
2,2026-07-31,Capitalisation flottante,44211442414.5,44211442414.5,NaN,NaN,NaN,NaN
3,2026-07-31,Capitalisation flottante,5272382579.4,NaN,NaN,NaN,NaN,5272382579.4
4,2026-07-31,Capitalisation flottante,7073577455.088,NaN,NaN,7073577455.088,NaN,NaN

Processing Données Marché Boursier_Projet_IA_copy.xlsx
Parsed sheet Data -> 220 rows
Parsed sheet Cours -> 98 rows
Parsed sheet Bid -> 98 rows
Parsed sheet Ask -> 98 rows
Parsed sheet Quantité MC -> 98 rows
Parsed sheet Volume MC -> 98 rows
Warning: failed to parse sheet Indicateurs: CODE ISIN row not found in sheet Indicateurs
Unified shape for Données Marché Boursier_Projet_IA_copy.xlsx : (261, 9)

,Date,CODE_ISIN,Company,Ask,Bid,Cours,Data,Quantité MC,Volume MC
0,2018-12-31,MA0000010936,ALUMINIUM DU MAROC,NaN,NaN,1565.0,NaN,NaN,NaN
1,2018-12-31,MA0000010944,AGMA,NaN,NaN,3079.0,NaN,NaN,NaN
2,2018-12-31,MA0000010951,AFRIQUIA GAZ,NaN,NaN,3000.0,NaN,NaN,NaN
3,2018-12-31,MA0000011819,ALLIANCES,NaN,NaN,85.0,NaN,23948.0,2035313.55
4,2018-12-31,MA0000012114,AFRIC INDUSTRIES SA,NaN,NaN,270.0,NaN,NaN,NaN

Processing Data_sheet_without_legend.xlsx
Warning: failed to parse sheet Feuille 1: 'str' object has no attribute 'astype'
Unified shape for Data_sheet_without_legend.xlsx : (0, 0)

Empty DataFrame
Columns: []
Index: []